---
title: "A06 & 7 Elemental confounds"
author: "David Mendez"
date: "2026-03-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Book

## 9.1. Goog king Markov and his island kingdom

```{r}
library(rethinking)
num_weeks <- 1e5
positions <- rep(0, num_weeks)
current <- 10
for (i in 1:num_weeks){
        positions[i] <- current
        proposal <- current + sample (c(-1,1),size=1)
        if (proposal < 1) proposal <- 10
        if (proposal > 10) proposal <- 1
        prob_move <- proposal/current
        current <-  ifelse(runif(1)<prob_move, proposal, current)
}
plot(1:100, positions[1:100])
plot(table(positions))
```

## 9.2. Metropolis algorithms

```{r}
D <- 10
T <- 1e3
Y <- rmvnorm(T, rep(0,D),diag(D))
rad_dist <- function(Y) sqrt(sum(Y^2))
Rd <- sapply(1:T, function(i) rad_dist(Y[i,]))
dens(Rd)
```

## 9.4. Easy HMC: ulam

```{r}
library(rethinking)
data("rugged")
d <- rugged
d$log_gdp <- log(d$rgdppc_2000)
dd <- d[complete.cases(d$rgdppc_2000),]
dd$log_gdp_std <- dd$log_gdp / mean(dd$log_gdp)
dd$rugged_std <- dd$rugged / max(dd$rugged)
dd$cid <- ifelse(dd$cont_africa==1,1,2)
```

```{r}
m8.3 <- quap(
        alist(
                log_gdp_std ~dnorm(mu, sigma),
                mu <- a[cid] + b[cid]*(rugged_std - 0.215),
                a[cid] ~ dnorm(1,0.1),
                b[cid] ~dnorm (0, 0.3),
                sigma ~dexp(1)
        ), data=dd
)
precis(m8.3, depth=2)
```

```{r}
dat_slim <- list(
        log_gdp_std = dd$log_gdp_std,
        rugged_std = dd$rugged_std,
        cid = as.integer(dd$cid)
)
m9.1 <- ulam(
        alist(
                log_gdp_std ~ dnorm(mu, sigma),
                mu <- a[cid] + b[cid]*(rugged_std - 0.215),
                a[cid] ~ dnorm(1,0.1),
                b[cid] ~ dnorm(0, 0.3),
                sigma ~dexp(1)
        ), data=dat_slim, chains=1
)
precis(m9.1, depth=2)
```

# Practice

## Easy

## Medium

## Hard

## Extra
