---
title: "A10 and A11 Mixed models"
author: "David Mendez"
date: "2026-03-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Book

## 11.1. Binomial regression

```{r}
library(rethinking)
data(chimpanzees)
d <- chimpanzees
d$treatment <- 1 + d$prosoc_left +2*d$condition
xtabs(~treatment + prosoc_left + condition, d)
m11.1 <- quap(
        alist(
                pulled_left ~ dbinom(1,p),
                logit(p) <- a,
                a ~dnorm(0,1)
        ),data=d
)
```

```{r}
set.seed(1999)
prior <- extract.prior(m11.1,n=1e4)
p <- inv_logit(prior$a)
dens(p, adj = 0.1)
```

```{r}
m11.2 <- quap(
        alist(
                pulled_left ~ dbinom(1,p),
                logit(p) <- a + b[treatment],
                a ~ dnorm(0,1.5),
                b[treatment] ~ dnorm(0,10)
        ), data=d
)
set.seed(1999)
prior <- extract.prior(m11.2,n=1e4)
p <- sapply(1:4,function(k) inv_logit(prior$a +prior$b[,k]))
dens(abs(p[,1]-p[,2]), adj=0.1)
```

```{r}
m11.3 <- quap(
        alist(
                pulled_left ~ dbinom(1,p),
                logit(p) <- a + b[treatment],
                a ~ dnorm(0,1.5),
                b[treatment] ~ dnorm(0,0.5)
        ), data=d
)
set.seed(1999)
prior <- extract.prior(m11.3,n=1e4)
p <- sapply(1:4,function(k) inv_logit(prior$a +prior$b[,k]))
#dens(abs(p[,1]-p[,2]), adj=0.1)
mean(abs(p[,1]-p[,2]))
```

```{r}
dat_list <- list(
        pulled_left = d$pulled_left,
        actor=d$actor,
        treatment = as.integer(d$treatment)
)
m11.4 <- ulam(
        alist(
                pulled_left ~ dbinom(1,p),
                logit(p) <- a[actor] + b[treatment],
                a[actor] ~ dnorm(0,1.5),
                b[treatment] ~ dnorm(0,0.5)
        ), data=dat_list, chains = 4,log_lik = T
)
precis(m11.4,depth=2)
post <- extract.samples(m11.4)
p_left <- inv_logit(post$a)
plot(precis(as.data.frame(p_left)),xlim=c(0,1))
labs <- c("R/N","L/N","R/P","L/P")
plot(precis(m11.4, depth = 2, pars="b"), labels=labs)
diffs <- list(
        db13 = post$b[,1] - post$b[,3],
        db24 = post$b[,2] - post$b[,4]
)
plot(precis(diffs))
pl <- by(d$pulled_left, list(d$actor, d$treatment), mean)
pl[1,]
dat <- list(actor=rep(1:7, each=4), treatment=rep(1:4, times=7))
p_post <- link(m11.4, data=dat)
p_mu <- apply(p_post, 2, mean)
p_ci <- apply(p_post, 2, PI)

```

```{r}
d$side <- d$prosoc_left + 1
d$cond <- d$condition + 1
dat_list2 <- list(
        pulled_left = d$pulled_left,
        actor=d$actor,
        side=d$side,
        cond = d$cond
)
m11.5 <- ulam(
        alist(
                pulled_left ~ dbinom(1,p),
                logit(p) <- a[actor] + bs[side] + bc[cond],
                a[actor] ~ dnorm(0,1.5),
                bc[cond] ~ dnorm(0,0.5),
                bs[side] ~ dnorm(0,0.5)
        ), data=dat_list2, chains = 4,log_lik = T
)
compare(m11.5, m11.4, func=PSIS)

```

### 11.1.3. Aggregated binomial: chimpanzees again, condensed.

```{r}
data("chimpanzees")
d <- chimpanzees
d$treatment <- 1 + d$prosoc_left + 2*d$condition
d$side <- d$prosoc_left + 1
d$cond <- d$condition + 1
d_aggregated <- aggregate(
        d$pulled_left,
        list(
                treatment = d$treatment, 
                actor = d$actor,
                side = d$side,
                cond = d$cond
        ), sum
)
colnames(d_aggregated)[5] <- "left_pulls"
dat <- with(
        d_aggregated, list(
                left_pulls = left_pulls,
                treatment = treatment,
                actor  = actor,
                side = side,
                cond = cond
        )
)

m11.6 <- ulam(
        alist(
                left_pulls ~ dbinom(18, p),
                logit(p) <- actor[actor]+ b[treatment],
                a[actor] ~ dnorm(0, 1.5),
                b[treatment] ~ dnorm(0,0.5)
        ), data=dat, chains=4, log_lik=T
)
compare(m11.6, m11.4, func = PSIS)
```

### 11.1.4. Aggregated binomial: Graduate school admissions

```{r}
library(rethinking)
data("UCBadmit")
d <- UCBadmit 
dat_list <- list(
        admit = d$admit,
        applications = d$applications,
        gid = ifelse(d$applicant.gender=="male",1,2)
)
m11.7 <- ulam(
        alist(
                admit ~ dbinom(applications, p),
                logit(p) <- a[gid],
                a[gid] ~ dnorm(0,1.5)
        ), data=dat_list, chains=4
)
precis(m11.7, depth=2)
post <- extract.samples(m11.7)
diff_a <- post$a[,1] - post$a[,2]
diff_p <- inv_logit(post$a[,1]) - inv_logit(post$a[,2])
precis(list(diff_a=diff_a, diff_p=diff_p))
postcheck(m11.7)
for (i in 1:6){
        x <- 1+2*(i-1)
        y1 <- d$admit[x]/d$applications[x]
        y2 <- d$admit[x+1]/d$applications[x+1]
        lines(c(x,x+1),c(y1,y2),col=rangi2, lwd=2)
        text(x+0.5, (y1+y2)/2 +0.05, d$dept[x], cex=0.8, col=rangi2)
}
```

```{r}
dat_list$dept_id <- rep(1:6, each=2)
m11.8 <- ulam(
        alist(
                admit ~ dbinom(applications, p),
                logit(p) <- a[gid] + delta[dept_id],
                a[gid] ~ dnorm(0,1.5),
                delta[dept_id] ~ dnorm(0,1.5)
        ), data=dat_list, chains=4, iter=4000
)
precis(m11.8,depth=2)
post <- extract.samples(m11.8)
diff_a <- post$a[,1] - post$a[,2]
diff_p <- inv_logit(post$a[,1]) - inv_logit(post$a[,2])
precis(list(diff_a=diff_a, diff_p=diff_p))
pg <- with(dat_list, sapply(1:6, 
                            function(k)
                            applications[dept_id == k]/sum(applications[dept_id==k])
        ))
rownames(pg) <- c("male","female")
colnames(pg) <- unique(d$dept)
round(pg,2)
```

## 11.2 Poisson regression

```{r}
y <- rbinom(1e5, 1e3, 1/1e3)
c(mean(y), var(y))
data("Kline")
d <- Kline
d$P <- scale(log(d$population))
d$contact_id <- ifelse(d$contact == "high",2,1)
curve(dlnorm(x,0,10),from=0, to=100, n=220)
curve(dlnorm(x,3,0.5),from=0, to=100, n=220)

```

```{r}
dat <- list(
        T = d$total_tools,
        P = d$P,
        cid = d$contact_id
)
m11.9 <- ulam(
        alist(
                T ~ dpois(lambda),
                log(lambda) <- a,
                a ~dnorm(3, 0.5)
        ), data=dat, chains =4, log_lik=T
)
m11.10 <- ulam(
        alist(
                T ~ dpois(lambda),
                log(lambda) <- a[cid]+b[cid]*P,
                a[cid] ~ dnorm(3, 0.5),
                b[cid] ~ dnorm(0, 0.2)
        ), data=dat, chains =4, log_lik=T
)
compare(m11.9, m11.10, func=PSIS)


```

# Practice

## Easy

## Medium

## Hard

## Extra
